## Introduction to choice-learn's modelling

In [ ]:
import os

os.environ["CUDA_VISIBLE_DEVICES"] = ""

import sys
from pathlib import Path

sys.path.append("../")

import numpy as np
import pandas as pd

### ChoiceModel - Getting Started

choice-learn package offers a high level API to conceive and estimate discrete choice models.

We begin this tutorial with the estimation of a Conditional Logit Model on the ModeCanada dataset.

First, we download our data as a ChoiceDataset. See the data management tutorial first if needed.

In [ ]:
from choice_learn.datasets import load_modecanada

transport_df = load_modecanada(as_frame=True)

# Following torch-choice guide:
transport_df = transport_df.loc[transport_df.noalt == 4]

items = ["air", "bus", "car", "train"]

transport_df["oh_air"] = transport_df.apply(lambda row: 1. if row.alt == items[0] else 0., axis=1)
transport_df["oh_bus"] = transport_df.apply(lambda row: 1. if row.alt == items[1] else 0., axis=1)
transport_df["oh_car"] = transport_df.apply(lambda row: 1. if row.alt == items[2] else 0., axis=1)
transport_df["oh_train"] = transport_df.apply(lambda row: 1. if row.alt == items[3] else 0., axis=1)

transport_df.income = transport_df.income.astype("float32")

In [ ]:
from choice_learn.data import ChoiceDataset
dataset = ChoiceDataset.from_single_df(df=transport_df,
                                       items_features_columns=["oh_air", "oh_bus", "oh_car", "oh_train"],
                                       sessions_features_columns=["income"],
                                       sessions_items_features_columns=["cost", "freq", "ovt", "ivt"],
                                       items_id_column="alt",
                                       sessions_id_column="case",
                                       choices_column="choice",
                                       choice_mode="one_zero")

Now, we can import the needed modules:

In [ ]:
from choice_learn.models import ConditionalMNL, ModelSpecification

The conditional MNL \ref{Train} specifies a linear utility for each item i during the session s with regards to the features:
$$
U(i, s) = \sum_{features} a(i, s) * feat(i, s)
$$

We will use a ModelSpecification object to define our model with regards to our ChoiceDataset.
For each feature in the choice dataset we can specify how it must be specified in the utility.

Let's re-use a common example from \ref{} on the ModeCanda dataset:
$$
U(i, s) = \beta^{inter}_i + \beta^{price} \cdot price(i, s) + \beta^{freq} \cdot freq(i, s) + \beta^{ovt} \cdot ovt(i, s) + \beta^{income}_i \cdot income(s) + \beta^{ivt}_i \cdot ivt(i, t) + \epsilon(i, t)
$$

Note that we want to estimate:

- one $\beta^{price}$, $\beta^{freq}$ and $\beta^{ovt}$ coefficient. They are shared by all items.
- one $\beta^{ivt}$ coefficient for **each** item.
- one $\beta^{inter}$ and $\beta^{income}$ coefficient for **each** item, with **additional constraint** to be 0 for the first item (air).

We will use a ModelSpecification object to create the right utility function.
We need to specify for each weight:
- a unique name
- the name of the feature it goes with:
    - it must match the feature name in the ChoiceDataset
    - "intercept" is the standardized name used for intercept, pay attention not to override it
- items_indexes: the items concerned, as indexed in the ChoiceDataset

In [ ]:
# Instantiation of the specification
spec = ModelSpecification()

# Creation of the different weights:


# add_coefficients adds one coefficient for each specified item_index
# intercept, and income are added for each item except the first one that needs to be zeroed
spec.add_coefficients(coefficient_name="beta_inter", feature_name="intercept", items_indexes=[1, 2, 3])
spec.add_coefficients(coefficient_name="beta_income", feature_name="income", items_indexes=[1, 2, 3])

# ivt is added for each item:
spec.add_coefficients(coefficient_name="beta_ivt", feature_name="ivt", items_indexes=[0, 1, 2, 3])

# shared_coefficient add one coefficient that is used for all items specified in the items_indexes:
# Here, cost, freq and ovt coefficients are shared between all items
spec.add_shared_coefficient(coefficient_name="beta_cost", feature_name="cost", items_indexes=[0, 1, 2, 3])
spec.add_shared_coefficient(coefficient_name="beta_freq", feature_name="freq", items_indexes=[0, 1, 2, 3])
spec.add_shared_coefficient(coefficient_name="beta_ovt", feature_name="ovt", items_indexes=[0, 1, 2, 3])

Now, we can instantiate our ConditionalMNL from the specification. We use LBFGS as the estimation method.

In [ ]:
cmnl = ConditionalMNL(spec, optimizer="lbfgs")

In order to estimate the the coefficients values, use the .fit method with the ChoiceDataset:

In [ ]:
history = cmnl.fit(dataset, n_epochs=1000)

It is possible to see the estimated coefficients with the .weights argument:

In [ ]:
cmnl.weights

[<tf.Variable 'beta_inter:0' shape=(1, 3) dtype=float32, numpy=array([[0.6983714, 1.8441044, 3.2741895]], dtype=float32)>,
 <tf.Variable 'beta_income:0' shape=(1, 3) dtype=float32, numpy=array([[-0.08908695, -0.02799302, -0.03814653]], dtype=float32)>,
 <tf.Variable 'beta_ivt:0' shape=(1, 4) dtype=float32, numpy=
 array([[ 0.05950955, -0.00678366, -0.00646027, -0.00145035]],
       dtype=float32)>,
 <tf.Variable 'beta_cost:0' shape=(1, 1) dtype=float32, numpy=array([[-0.03333883]], dtype=float32)>,
 <tf.Variable 'beta_freq:0' shape=(1, 1) dtype=float32, numpy=array([[0.09252933]], dtype=float32)>,
 <tf.Variable 'beta_ovt:0' shape=(1, 1) dtype=float32, numpy=array([[-0.04300348]], dtype=float32)>]

The negative loglikelihood can be estimated using .evaluate():

In [ ]:
print("The average neg-loglikelihood is:", cmnl.evaluate(dataset).numpy())
print("The total neg-loglikelihood is:", cmnl.evaluate(dataset).numpy()*len(dataset))

The average neg-loglikelihood is: 0.674474
The total neg-loglikelihood is: 1874.3632485866547


We can compare the estimated coefficients and the negative log-likelihood obtained in \ref{} and \ref{torch-choice}, and it is similar !

In [ ]:
import tensorflow as tf

# Here are the values obtained in the references:
gt_weights = [
    tf.constant([[0.697311, 1.8437, 3.27381]]),
    tf.constant([[-0.0890796, -0.0279925, -0.038146]]),
    tf.constant([[0.0595089, -0.00678188, -0.00645982, -0.00145029]]),
    tf.constant([[-0.0333421]]),
    tf.constant([[0.0925304]]),
    tf.constant([[-0.0430032]]),
]
gt_model = ConditionalMNL(spec, lr=0.01)
gt_model.fit(dataset, n_epochs=1, batch_size=-1)

# Here we estimate the negative log-likelihood with these coefficients (also, we obtain same value as in those papers):
gt_model.weights = gt_weights
print("'Ground Truth' Negative LogLikelihood:", gt_model.evaluate(dataset) * len(dataset))

100%|██████████| 1/1 [00:01<00:00,  1.30s/it]


'Ground Truth' Negative LogLikelihood: tf.Tensor(1874.363, shape=(), dtype=float32)


In order to estimate the utilities, use the .predict_utility() method. In order to estimate the probabilities, use the .compute_probabilities() method.


In [ ]:
# print("Utilities of each item for the first 5 sessions:", cmnl.predict_utility(dataset)[:5])
print("Purchase probability of each item for the first 5 sessions:", cmnl.predict_probas(dataset)[:5])

Purchase probability of each item for the first 5 sessions: tf.Tensor(
[[0.19061294 0.00353295 0.40536764 0.40048242]
 [0.34869465 0.00069692 0.36830828 0.28229645]
 [0.14418268 0.00651326 0.4056784  0.4436212 ]
 [0.34869465 0.00069692 0.36830828 0.28229645]
 [0.34869465 0.00069692 0.36830828 0.28229645]], shape=(5, 4), dtype=float32)


In [ ]:
import matplotlib.pyplot as plt
plt.plot(history)

For very large datasets that do not fit entirely in the memory, the LBFGS method might not be the best choice. Here we can use the power of the Tensorflow library to use stochastic gradient descent optimizers.

In this case, it is possible to obtain the same coefficients estimation, also it is a little tricky to get it quickly. We need to adjust the learning rate over time for the optimization not to be too slow.

In [ ]:
cmnl = ConditionalMNL(spec, optimizer="Adam")
history = cmnl.fit(dataset, n_epochs=2000, batch_size=-1)
cmnl.optimizer.lr = cmnl.optimizer.lr / 5
history2 = cmnl.fit(dataset, n_epochs=4000, batch_size=-1)
cmnl.optimizer.lr = cmnl.optimizer.lr  / 10
history3 = cmnl.fit(dataset, n_epochs=20000, batch_size=-1)

In [ ]:
cmnl.weights

[<tf.Variable 'beta_inter:0' shape=(1, 3) dtype=float32, numpy=array([[-1.6874468 , -0.39640382,  1.1344575 ]], dtype=float32)>,
 <tf.Variable 'beta_income:0' shape=(1, 3) dtype=float32, numpy=array([[-0.08402976, -0.02359828, -0.03233591]], dtype=float32)>,
 <tf.Variable 'beta_ivt:0' shape=(1, 4) dtype=float32, numpy=
 array([[ 0.05871165, -0.00726177, -0.003686  , -0.00105613]],
       dtype=float32)>,
 <tf.Variable 'beta_cost:0' shape=(1, 1) dtype=float32, numpy=array([[-0.05141076]], dtype=float32)>,
 <tf.Variable 'beta_freq:0' shape=(1, 1) dtype=float32, numpy=array([[0.09645191]], dtype=float32)>,
 <tf.Variable 'beta_ovt:0' shape=(1, 1) dtype=float32, numpy=array([[-0.04099193]], dtype=float32)>]

In [ ]:
cmnl.evaluate(dataset)

<tf.Tensor: shape=(), dtype=float32, numpy=0.676656>

A faster specification can be done using a dictionnary. It follows torch-choice \ref{} method to create conditional logit models.
The parameters dict needs to be as follows:
- The key is the feature name
- The value is the mode. Currently three modes are available:
    - constant: the learned coefficient is shared by all items
    - item: one coefficient by item is estimated, the value for the item at index 0 is set to 0
    - item-full: one coefficient by item is estimated

In order to create the same model for the ModeCanada dataset, it looks as follows:

In [ ]:
# Instantiation of the parameters dictionnary
params = {"income": "item",
 "cost": "constant", 
 "freq": "constant",
 "ovt": "constant", 
 "ivt": "item-full",
 "intercept": "item"}

# Instantiation of the model
cmnl = ConditionalMNL(parameters=params, optimizer="lbfgs")

In [ ]:
history = cmnl.fit(dataset, n_epochs=1000)
print(cmnl.weights)

Feature oh_air is in dataset but has no weight assigned in utility                            computations
Feature oh_bus is in dataset but has no weight assigned in utility                            computations
Feature oh_car is in dataset but has no weight assigned in utility                            computations
Feature oh_train is in dataset but has no weight assigned in utility                            computations
L-BFGS Opimization finished:
---------------------------------------------------------------
Number of iterations: 170
Algorithm converged before reaching max iterations: True
[<tf.Variable 'income:0' shape=(1, 3) dtype=float32, numpy=array([[-0.08908867, -0.02799244, -0.03814625]], dtype=float32)>, <tf.Variable 'cost:0' shape=(1, 1) dtype=float32, numpy=array([[-0.03333894]], dtype=float32)>, <tf.Variable 'freq:0' shape=(1, 1) dtype=float32, numpy=array([[0.09252954]], dtype=float32)>, <tf.Variable 'ovt:0' shape=(1, 1) dtype=float32, numpy=array([[-0.04300347]], 